title: FRC 7617 Code Standards
description: Code standards documentation for FRC team 7617.
theme: just-the-docs

url: https://CoffeeCoder1.github.io/7617-code-standards

# Aux links in the navbar
aux_links:
  "7617 GitHub":
    - "https://github.com/roboblazers7617"
